print(3 + 6)
print(5 - 7)
print(5 * 3)
print(899 % 10)
print(3 / 5)  
print(3 ** 6)
print(6 // 7)
#Nombre, Apellido y Pais 
print("Isaac Santos Verdeja")
print('Santos Verdeja')
print('Mexico')
print('I am enjoy 30 days of python')
#checking data types 

print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4-4j))
print(type(['Asabeneh','Python','finland']))
print(type(['Isaac Santos Verdeja']))
print(type('Santos Verdeja'))
print(type('Mexico'))
