print(3 + 6)
print(5 - 7)
print(5 * 3)
print(899 % 10)
print(3 / 5)  
print(3 ** 6)
print(6 // 7)
#Nombre, Apellido y Pais 
print("Aldo Santiago Fernandez Gomez")
print('Fernandez Gomez')
print('Mexico')
print('I am enjoy 30 days of python')
#checking data types 

print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4-4j))
print(type(['Asabeneh','Python','finland']))
print(type(['Aldo Santiago Fernandez Gomez']))
print(type('Fernandez Gomez'))
print(type('Mexico'))
